dist: trusty
sudo: false
language: node_js
codecov: true
notifications:
  email: false
cache:
  directories:
    - "~/.npm"
    - "~/.cache"
node_js:
  - 12.16.3
install:
  - npm install
script:
  - npm run ci
after_success:
  - codecov
