
codecov:
  token: a050f8b9-7ebf-47f1-ae89-2bf23637e4ae
  require_ci_to_pass: yes

coverage:
  precision: 2
  round: down
  range: "70...100"

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no
  javascript:
    enable_partials: yes

comment:
  layout: "reach,diff,flags,tree"
  behavior: default
  require_changes: no
